fix/typecheck errors
TFK70/academy-test pull request #5
Opened 2022-11-21 14:07 UTC by eshevlyakova

2022-11-22 19:49 UTC, TFK70 requested changes
Выполнены не все задания. У тебя же проект не отрисовывается

2022-11-22 19:49 UTC, TFK70 commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
А почему так?) Какая здесь ошибка?

2022-11-23 16:22 UTC, eshevlyakova commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
Здесь ошибка в том, что node возможно равен null. Но я не понимаю как ее исправить

2022-11-23 16:43 UTC, TFK70 commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
И в чём он здесь не прав?

2022-11-23 16:54 UTC, eshevlyakova commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
Он прав. Но если я уберу null из useRef(), то будет ошибка: `Error: Object is possibly 'undefined'.`, и он тоже будет прав. 
Я не понимаю на что нужно заменить null

2022-11-23 16:56 UTC, TFK70 commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
Ты немного не в том направлении мыслишь
Ты обращаешься к свойству `current` у `node`, но у `null` ведь такого свойства нет. То есть если у тебя что-то пойдёт не так и node будет нуллом - то произойдёт ошибка. Как это можно предотвратить?

2022-11-24 07:39 UTC, eshevlyakova commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
Я только догадалась сделать проверку:
```typescript
if (node != null) {
      node.current.style.color = colors[floor(random() * 3)]
    }
```
Но ошибка осталась

2022-11-24 09:08 UTC, TFK70 commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
`if (node)` достаточно будет
И ошибки не должно быть

2022-11-24 09:33 UTC, eshevlyakova commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
<img width="566" alt="Снимок экрана 2022-11-24 в 12 32 47" src="https://user-images.githubusercontent.com/79781486/203748393-c748f0b5-192c-4a0d-83cb-7d095b99d9d9.png">
И ошибка осталась:

```shell
Error: Object is possibly 'null'.
➤ YN0000: │ 
➤ YN0000: │    9 |   useEffect(() => {
➤ YN0000: │   10 |     if (node) {
➤ YN0000: │ > 11 |       node.current.style.color = colors[floor(random() * 3)]
➤ YN0000: │      |      ^
➤ YN0000: │   12 |     }
➤ YN0000: │   13 |   }, [])

```

2022-11-24 10:17 UTC, TFK70 commented on frontend/fragments/landing-state-action/src/hooks/useRandomColor.ts
> +    // @ts-ignore
@eshevlyakova можешь сделать так

```typescript
if (node && node.current) {
      (node.current as any).style.color = colors[floor(random() * 3)]
    }
```

Там кривые типы, он не видит style в current, так что можешь пока присвоить его в any

А чтобы не было ошибки с null/undefined - нужно сделать дополнительную проверку на `node.current`

2022-11-24 11:39 UTC, eshevlyakova commented
@TFK70 
Можешь пожалуйста обьяснить что происходит в [этом файле](https://github.com/eshevlyakova/academy-test/blob/fix/typecheck-errors/frontend/fragments/landing-state-action/src/helpers/message.ts)?
В первой строке создается переменная со строкой. В третьей строке создается новый тип, который принимает и возвращает строку.
А вот в 5 строке я не совсем понимаю, что происходит

2022-11-24 12:07 UTC, TFK70 commented
> этом файле

Не могу, в этом и задумка, тебе нужно самой разобраться в происходящем

2022-11-24 13:35 UTC, eshevlyakova commented
@TFK70 
Исправила ошибки `yarn check`, но сайт не запускается

2022-11-25 09:14 UTC, closed without merging